name: Deploy Firebase Functions

# Controls when the workflow will run
on:
  push:
    branches:
      - main    # Triggers the workflow on push to the 'main' branch
  workflow_dispatch:  # Allows manual triggering

# Workflow jobs
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the Node.js version that matches Firebase functions

      # Install Firebase CLI globally
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Install dependencies
      - name: Install dependencies
        run: cd functions/ && npm install

      # Deploy Firebase Functions
      - name: Deploy Firebase Functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: cd functions/ && npm run-script deploy

