name: Deploy Firebase Functions

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - uat
  workflow_dispatch:  # Allows manual triggering

# Workflow jobs
jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: functions

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the Node.js version that matches Firebase functions

      - name: Set Environment Variables
        env:
          GOOGLE_APPLICATION_CREDENTIALS_UAT: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_UAT }}
          GOOGLE_APPLICATION_CREDENTIALS_PRO: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
            echo "Environment variables set"
  

      # Install Firebase CLI globally
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Choose environment based on branch
      - name: Select Firebase project environment
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "Deploying to production environment"
            firebase use default
          elif [ "${{ github.ref }}" == "refs/heads/uat" ]; then
            echo "Deploying to uat environment"
            firebase use uat
          else
            echo "No environment matched for this branch"
            exit 1
          fi

      # Deploy Firebase Functions
      - name: Deploy Firebase Functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: npm run-script deploy

