name: Deploy Firebase Functions

on:
  push:
    branches:
      - main
      - uat
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: functions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set GOOGLE_APPLICATION_CREDENTIALS for uat
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_UAT }}" > ${{ github.workspace }}/credentials-uat.json
        if: github.ref == 'refs/heads/uat'
  
      - name: Set GOOGLE_APPLICATION_CREDENTIALS for Production
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > ${{ github.workspace }}/credentials-pro.json
        if: github.ref == 'refs/heads/main'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: npm install

      - name: Set Environment Variables for Storage and Credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS_PRO: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          GOOGLE_APPLICATION_CREDENTIALS_UAT: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_UAT }}
          STORAGE_BUCKET_PRO: ${{ secrets.STORAGE_BUCKET_PRO }}
          STORAGE_BUCKET_UAT: ${{ secrets.STORAGE_BUCKET_UAT }}
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Using production environment variables"
            touch service-account-pro.json
            echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > service-account-pro.json
            echo NODE_ENV=pro >> $GITHUB_ENV
            echo "GOOGLE_APPLICATION_CREDENTIALS_PRO=${{ github.workspace }}/service-account-pro.json" >> $GITHUB_ENV
            echo "STORAGE_BUCKET_PRO=${{ secrets.STORAGE_BUCKET_PRO }}" >> $GITHUB_ENV
          else
            echo "Using uat environment variables"
            touch service-account-uat.json
            echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_UAT }}" > service-account-uat.json
            echo "Github workspace : ${{ github.workspace }}"
            echo "Pwd: $(pwd)"
            pwd
            ls
            cat service-account-uat.json
            echo NODE_ENV=uat >> $GITHUB_ENV
            echo GOOGLE_APPLICATION_CREDENTIALS_UAT=$(pwd)/service-account-uat.json >> $GITHUB_ENV
            echo "STORAGE_BUCKET_UAT=${{ secrets.STORAGE_BUCKET_UAT }}" >> $GITHUB_ENV
            env
          fi

      - name: Select Firebase project environment
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "Deploying to production environment"
            firebase use default
          elif [ "${{ github.ref }}" == "refs/heads/uat" ]; then
            echo "Deploying to uat environment"
            firebase use uat
          else
            echo "No environment matched for this branch"
            exit 1
          fi

      - name: Deploy Firebase Functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS_PRO: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          GOOGLE_APPLICATION_CREDENTIALS_UAT: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_UAT }}
          STORAGE_BUCKET_PRO: ${{ secrets.STORAGE_BUCKET_PRO }}
          STORAGE_BUCKET_UAT: ${{ secrets.STORAGE_BUCKET_UAT }}
        run: |
          npm run deploy
